(function(){
  "use strict";
  const MODULES={
    hyperbolic:{title:"noixzy hyperbolic horocycle garden",concept:"Poincare disk arcs, nested horocycles, and impossible garden paths.",accent:"#9fc6d0",seed:"hyperbolic-horocycle-001",controls:[["rings",3,22,1,11],["geodesics",4,80,1,34],["curvature",0,100,1,62],["node density",0,100,1,48],["line weight",1,7,1,2],["bump",0,100,1,35],["rotation",-100,100,1,12],["palette",0,5,1,2]]},
    inversion:{title:"noixzy circle inversion shrine",concept:"Circle inversion chains with recursive halos, tangent gates, and relic rings.",accent:"#d8c089",seed:"circle-inversion-001",controls:[["seed circles",3,18,1,8],["recursion",1,7,1,4],["inversion radius",20,160,1,78],["halo density",0,100,1,52],["line weight",1,8,1,2],["extrude",0,100,1,38],["jitter",0,100,1,12],["palette",0,5,1,4]]},
    clifford:{title:"noixzy clifford attractor loom",concept:"Chaotic Clifford point clouds woven into luminous textile currents.",accent:"#c3a6df",seed:"clifford-loom-001",controls:[["point count",1000,18000,1,6200],["a",-300,300,1,170],["b",-300,300,1,-180],["c",-300,300,1,160],["d",-300,300,1,-120],["exposure",0,100,1,44],["dot size",1,5,1,1],["palette",0,5,1,5]]},
    dunes:{title:"noixzy perlin dune ridgelines",concept:"Anisotropic dune ridges, wind shear contours, and sand-etched relief lines.",accent:"#d8c89f",seed:"dune-ridges-001",controls:[["ridge count",8,90,1,42],["wind shear",-100,100,1,36],["noise scale",5,90,1,34],["amplitude",0,100,1,58],["grain",0,100,1,42],["line weight",1,6,1,1],["contour gap",4,28,1,10],["palette",0,5,1,0]]},
    foam:{title:"noixzy voronoi foam relief",concept:"Foam cell mosaics with raised membranes, nucleation points, and packed voids.",accent:"#a9cab8",seed:"foam-relief-001",controls:[["seed count",8,180,1,74],["cell size",4,18,1,8],["membrane",0,100,1,55],["void bias",0,100,1,36],["bump",0,100,1,46],["line weight",1,7,1,2],["jitter",0,100,1,26],["palette",0,5,1,1]]},
    braid:{title:"noixzy braid group knotfield",concept:"Braid group crossings, knot traces, strand tension, and woven signal columns.",accent:"#9db7d6",seed:"braid-knotfield-001",controls:[["strands",3,18,1,8],["crossings",4,80,1,36],["tension",0,100,1,48],["amplitude",0,100,1,54],["phase",0,100,1,30],["line weight",1,8,1,2],["glow",0,100,1,36],["palette",0,5,1,2]]},
    csg:{title:"noixzy csg relic assembler",concept:"Constructive-solid-geometry plates, boolean cuts, sockets, and nano relic parts.",accent:"#cbb999",seed:"csg-relic-001",controls:[["parts",4,80,1,28],["cutouts",0,100,1,48],["socket density",0,100,1,42],["array spread",0,100,1,55],["extrude",0,100,1,52],["bump",0,100,1,32],["line weight",1,7,1,2],["palette",0,5,1,0]]},
    vein:{title:"noixzy reaction vein atlas",concept:"Branching reaction veins, pressure ridges, and mineral maps.",accent:"#d1a0a0",seed:"reaction-vein-001",controls:[["vein count",3,80,1,32],["branch depth",1,9,1,5],["pressure",0,100,1,54],["curl",-100,100,1,22],["mineral fill",0,100,1,48],["line weight",1,8,1,2],["bump",0,100,1,38],["palette",0,5,1,3]]},
    barcode:{title:"noixzy radial barcode topography",concept:"Polar barcodes, circular data strata, stepped topographic rings.",accent:"#d6cf9d",seed:"radial-barcode-001",controls:[["rings",8,120,1,52],["spokes",8,240,1,96],["gap chance",0,100,1,28],["height",0,100,1,50],["phase",0,100,1,20],["line weight",1,7,1,2],["marker density",0,100,1,38],["palette",0,5,1,4]]},
    masonryca:{title:"noixzy cellular masonry automata",concept:"Cellular automata brick courses, shifting mortar logic, and tower-like accretion.",accent:"#d2a487",seed:"masonry-ca-001",controls:[["grid",8,60,1,28],["states",2,8,1,4],["generations",4,80,1,32],["rule",0,255,1,110],["mortar",0,100,1,44],["extrude",0,100,1,38],["bump",0,100,1,34],["palette",0,5,1,3]]}
  };
  const PALETTES=[["#070707","#d8c9aa","#8fc8c2"],["#050706","#a8d0ad","#e4d8b6"],["#05080b","#9dc7ff","#e8c779"],["#090805","#d4bd84","#9bb7d2"],["#090606","#d2a487","#d8c9aa"],["#08070a","#c7b2df","#80d6d0"]];
  const TAU=Math.PI*2;
  function hash(t){let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
  function rng(seed){let t=hash(seed)||1;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^(t>>>15),1|t);r^=r+Math.imul(r^(r>>>7),61|r);return((r^(r>>>14))>>>0)/4294967296;};}
  function hsl(h,s,l,a){return 'hsla('+h+', '+s+'%, '+l+'%, '+a+')';}
  function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
  function rect3(ctx,x,y,w,h,d,fill){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);ctx.fillStyle='rgba(255,255,255,.10)';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+d,y-d*.45);ctx.lineTo(x+w+d,y-d*.45);ctx.lineTo(x+w,y);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.moveTo(x+w,y);ctx.lineTo(x+w+d,y-d*.45);ctx.lineTo(x+w+d,y+h-d*.45);ctx.lineTo(x+w,y+h);ctx.closePath();ctx.fill();}
  window.initNoixzyBatch16=function(id){
    const mod=MODULES[id];if(!mod)throw new Error('unknown batch 16 module: '+id);document.title=mod.title;
    const style=document.createElement('style');style.textContent=':root{color-scheme:dark;--a:'+mod.accent+';--t:#e8e1d4;--m:#8c877d}*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:#050505;color:var(--t);font-family:ui-monospace,SFMono-Regular,Menlo,monospace}body{display:grid;grid-template-columns:minmax(0,1fr) 292px}main{min-width:0;min-height:0;background:radial-gradient(circle at 50% 24%,rgba(255,255,255,.07),transparent 36%),linear-gradient(#101010,#020202)}canvas{display:block;width:100%;height:100%}aside{border-left:1px solid #2b2b2b;background:#101010;padding:14px;overflow:auto}h1{margin:0 0 5px;font-size:15px;text-transform:lowercase}.sub,.note{color:var(--m);font-size:11px;line-height:1.45}.buttons{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}button{height:34px;border:1px solid #373737;background:#171717;color:var(--t);font:inherit;font-size:11px;cursor:pointer}.row{display:grid;grid-template-columns:44px 1fr;gap:8px;align-items:center;margin-bottom:12px}.row span{font-size:11px;color:var(--m)}input[type=text]{width:100%;background:#080808;border:1px solid #343434;color:var(--t);padding:8px;font:inherit;font-size:11px}.control{border-top:1px solid #222;padding:9px 0}.head{display:flex;justify-content:space-between;font-size:11px;margin-bottom:6px;color:var(--m)}.head b{font-weight:400;color:var(--a)}input[type=range]{width:100%;accent-color:var(--a)}.physics-toggle{display:flex;align-items:center;gap:8px;margin:10px 0 12px;padding:9px 0;border-top:1px solid #222;border-bottom:1px solid #222;color:var(--m);font-size:11px;text-transform:lowercase}.physics-toggle input{accent-color:var(--a)}@media(max-width:760px){body{grid-template-columns:1fr;grid-template-rows:minmax(0,1fr) 315px}aside{border-left:0;border-top:1px solid #2b2b2b}}';document.head.appendChild(style);
    document.body.innerHTML='<main><canvas id="view"></canvas></main><aside><h1>'+mod.title+'</h1><p class="sub">'+mod.concept+'</p><div class="buttons"><button id="play">pause</button><button id="randomize">randomize</button><button id="reset">reset</button><button id="export">export png</button></div><div class="row"><span>seed</span><input id="seed" value="'+mod.seed+'" spellcheck="false"></div><div id="controls"></div><label class="physics-toggle"><input id="experimental-physics" type="checkbox"> experimental physics</label><p class="note">batch 16: generated algorithmic systems for the escrow shell; local geometry controls only.</p></aside>';
    const canvas=document.getElementById('view'),ctx=canvas.getContext('2d'),controls=document.getElementById('controls'),seedEl=document.getElementById('seed');
    const state=Object.fromEntries(mod.controls.map(c=>[c[0],c[4]]));let w=1,h=1,dpr=1,frame=0,running=true,physics=false;
    mod.controls.forEach(([key,min,max,step])=>{const div=document.createElement('div');div.className='control';div.innerHTML='<div class="head"><span>'+key+'</span><b>'+state[key]+'</b></div><input type="range" min="'+min+'" max="'+max+'" step="'+step+'" value="'+state[key]+'">';controls.appendChild(div);div.querySelector('input').oninput=e=>{state[key]=Number(e.target.value);div.querySelector('b').textContent=state[key];draw(true);};});
    function pal(){return PALETTES[Math.abs(Math.floor(state.palette||0))%PALETTES.length];}
    function snap(v,min,max,step){return clamp(Math.round(v/step)*step,min,max);}
    function bias(k){k=String(k).toLowerCase();if(/palette|rule/.test(k))return Math.random();if(/count|grid|rings|spokes|states|generations|depth|parts|cutouts|seed/.test(k))return .38+Math.random()*.62;if(/extrude|height|bump|density|weight|radius|amplitude|pressure/.test(k))return .25+Math.random()*.75;return .12+Math.random()*.76;}
    function randomize(){seedEl.value=id+'-'+Math.floor(Math.random()*999999).toString(36);controls.querySelectorAll('.control').forEach(div=>{const input=div.querySelector('input'),key=div.querySelector('.head span').textContent,min=+input.min,max=+input.max,step=+input.step||1,v=snap(min+(max-min)*bias(key),min,max,step);input.value=v;state[key]=v;div.querySelector('b').textContent=v;});physics=Math.random()>.55;document.getElementById('experimental-physics').checked=physics;applyPhysics();draw(true);}
    function applyPhysics(){canvas.style.transformOrigin='50% 50%';canvas.style.transform=physics?'translate3d('+Math.sin(frame*.017)*4+'px,'+Math.cos(frame*.013)*3+'px,0) scale('+(1+Math.sin(frame*.011)*.004)+')':'';canvas.style.filter=physics?'contrast(1.06) saturate(1.08)':'';}
    function resize(){dpr=Math.max(1,Math.min(2,devicePixelRatio||1));const r=canvas.getBoundingClientRect();w=Math.max(320,r.width);h=Math.max(260,r.height);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw(true);}
    function clear(){ctx.fillStyle=pal()[0];ctx.fillRect(0,0,w,h);}
    function draw(){clear();const p=pal(),R=rng(seedEl.value+id),cx=w/2,cy=h/2,t=frame*.012;ctx.lineCap='round';ctx.lineJoin='round';
      if(id==='hyperbolic'){let rad=Math.min(w,h)*.42;ctx.save();ctx.translate(cx,cy);ctx.rotate((state.rotation*.01+t*.2));ctx.strokeStyle=p[1];ctx.lineWidth=state['line weight'];ctx.beginPath();ctx.arc(0,0,rad,0,TAU);ctx.stroke();for(let i=0;i<state.rings;i++){ctx.globalAlpha=.45;ctx.beginPath();ctx.arc(0,0,rad*(i+1)/(state.rings+1),0,TAU);ctx.stroke();}ctx.globalAlpha=1;for(let i=0;i<state.geodesics;i++){let a=i*TAU/state.geodesics,b=a+Math.PI*(.28+state.curvature*.004);ctx.beginPath();ctx.arc(Math.cos(a)*rad*.2,Math.sin(a)*rad*.2,rad*(.2+state.curvature*.006),a,b);ctx.stroke();if(R()*100<state['node density']){ctx.fillStyle=p[2];ctx.beginPath();ctx.arc(Math.cos(a)*rad*R(),Math.sin(a)*rad*R(),1+state.bump*.02,0,TAU);ctx.fill();}}ctx.restore();}
      else if(id==='inversion'){for(let i=0;i<state['seed circles'];i++){let a=i*TAU/state['seed circles']+t*.1,r=state['inversion radius']*(.25+R()*.7),x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r*.72;for(let d=0;d<state.recursion;d++){let rr=r/(d+2);ctx.strokeStyle=d%2?p[1]:p[2];ctx.lineWidth=state['line weight']/(d+1);ctx.beginPath();ctx.arc(x+(R()-.5)*state.jitter*.2,y+(R()-.5)*state.jitter*.2,rr,0,TAU);ctx.stroke();if(R()*100<state['halo density'])rect3(ctx,x-rr*.25,y-rr*.15,rr*.5,rr*.3,state.extrude*.05,p[2]);}}}
      else if(id==='clifford'){let x=.1,y=.1,a=state.a/100,b=state.b/100,c=state.c/100,d=state.d/100;ctx.fillStyle='rgba(255,255,255,.03)';for(let i=0;i<state['point count'];i++){let nx=Math.sin(a*y)+c*Math.cos(a*x),ny=Math.sin(b*x)+d*Math.cos(b*y);x=nx;y=ny;let px=cx+x*Math.min(w,h)*.18,py=cy+y*Math.min(w,h)*.18;ctx.fillStyle=hsl(265+i*.01+state.palette*20,30,55,state.exposure/160);ctx.fillRect(px,py,state['dot size'],state['dot size']);}}
      else if(id==='dunes'){ctx.strokeStyle=p[1];ctx.lineWidth=state['line weight'];for(let i=0;i<state['ridge count'];i++){let y=h*(i+1)/(state['ridge count']+1);ctx.beginPath();for(let x=0;x<=w;x+=state['contour gap']){let v=Math.sin(x*.012+state['noise scale']*.04+i*.3)+Math.sin(x*.027+i+state['wind shear']*.02);let py=y+v*state.amplitude*.18+Math.sin((x+y)*.04)*state.grain*.03;x?ctx.lineTo(x,py):ctx.moveTo(x,py);}ctx.stroke();}}
      else if(id==='foam'){let seeds=[];for(let i=0;i<state['seed count'];i++)seeds.push([R()*w,R()*h]);let cs=state['cell size'];for(let y=0;y<h;y+=cs)for(let x=0;x<w;x+=cs){let best=1e9,idx=0;for(let i=0;i<seeds.length;i++){let dx=x-seeds[i][0],dy=y-seeds[i][1],dd=dx*dx+dy*dy;if(dd<best){best=dd;idx=i;}}let edge=Math.sqrt(best)%state.membrane;if(edge<state['line weight']||R()*100<state['void bias']*.01){ctx.fillStyle=hsl(140+idx%40+state.palette*20,22,22+state.bump*.08,.8);ctx.fillRect(x,y,cs,cs);}}}
      else if(id==='braid'){for(let s=0;s<state.strands;s++){ctx.strokeStyle=s%2?p[1]:p[2];ctx.lineWidth=state['line weight'];ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=state.glow*.08;ctx.beginPath();for(let i=0;i<=state.crossings;i++){let u=i/state.crossings,x=w*.1+u*w*.8,y=cy+(s-(state.strands-1)/2)*(h*.55/state.strands)+Math.sin(u*TAU*(2+state.phase*.03)+s+t)*state.amplitude*.45+Math.sin(u*TAU*state.strands+s)*state.tension*.08;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}ctx.shadowBlur=0;}
      else if(id==='csg'){for(let i=0;i<state.parts;i++){let x=w*(.12+R()*.76),y=h*(.12+R()*.76),ww=18+R()*state['array spread'],hh=12+R()*state['array spread']*.8;rect3(ctx,x,y,ww,hh,state.extrude*.08,i%2?p[1]:p[2]);if(R()*100<state.cutouts){ctx.fillStyle=pal()[0];ctx.fillRect(x+ww*.25,y+hh*.25,ww*.5,hh*.5);}if(R()*100<state['socket density']){ctx.fillStyle='#e8d8aa';ctx.beginPath();ctx.arc(x+ww*.5,y+hh*.5,2+state.bump*.02,0,TAU);ctx.fill();}}}
      else if(id==='vein'){function branch(x,y,len,a,d){if(d<=0)return;let nx=x+Math.cos(a)*len,ny=y+Math.sin(a)*len;ctx.strokeStyle=d%2?p[1]:p[2];ctx.lineWidth=Math.max(.6,state['line weight']*d/state['branch depth']);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(nx,ny);ctx.stroke();for(let k=0;k<2;k++)if(R()*100<state['mineral fill']+20)branch(nx,ny,len*(.55+R()*.25),a+(R()-.5)*state.pressure*.025+state.curl*.002*(k?1:-1),d-1);}for(let i=0;i<state['vein count'];i++)branch(R()*w,R()*h,20+state.pressure*.7,R()*TAU,state['branch depth']);}
      else if(id==='barcode'){for(let r=0;r<state.rings;r++){let rr=Math.min(w,h)*.04+r*Math.min(w,h)*.42/state.rings;for(let s=0;s<state.spokes;s++){if(R()*100<state['gap chance'])continue;let a=s*TAU/state.spokes+state.phase*.01,da=TAU/state.spokes*.75;ctx.strokeStyle=s%3?p[1]:p[2];ctx.lineWidth=state['line weight']+state.height*.012;ctx.beginPath();ctx.arc(cx,cy,rr,a,a+da);ctx.stroke();}}for(let i=0;i<state['marker density'];i+=3){ctx.fillStyle=p[2];ctx.fillRect(cx+(R()-.5)*w*.7,cy+(R()-.5)*h*.7,2,2);}}
      else if(id==='masonryca'){let n=state.grid,cs=Math.min(w,h)*.82/n,ox=(w-cs*n)/2,oy=(h-cs*n)/2,row=Array.from({length:n},()=>R()>.5?1:0);for(let y=0;y<n;y++){let next=[];for(let x=0;x<n;x++){let l=row[(x+n-1)%n],c=row[x],rr=row[(x+1)%n],code=(l<<2)|(c<<1)|rr,v=(state.rule>>code)&1;next[x]=v;let st=(v+y)%state.states;if(v||R()*100<state.bump*.08)rect3(ctx,ox+x*cs+(y%2)*cs*.22,oy+y*cs,cs-state.mortar*.03,cs*.72,state.extrude*.04,hsl(20+st*26+state.palette*16,28,18+st*5,.88));}row=next;}}
      ctx.globalAlpha=1;ctx.fillStyle='rgba(232,225,212,.68)';ctx.font='11px ui-monospace,monospace';ctx.fillText(seedEl.value,16,h-18);
    }
    function tick(){if(running){frame++;applyPhysics();draw(false);}requestAnimationFrame(tick);}document.getElementById('play').onclick=()=>{running=!running;document.getElementById('play').textContent=running?'pause':'play';draw(true);};document.getElementById('randomize').onclick=randomize;document.getElementById('reset').onclick=()=>location.reload();document.getElementById('export').onclick=()=>{draw(true);const a=document.createElement('a');a.download=id+'.png';a.href=canvas.toDataURL('image/png');a.click();};document.getElementById('experimental-physics').onchange=e=>{physics=e.target.checked;applyPhysics();draw(true);};seedEl.oninput=()=>draw(true);addEventListener('resize',resize);resize();tick();
  };
})();
