(function () {
  "use strict";

  const MODULES = {
    minimal_parti: {
      title: "noixzy minimal parti",
      concept: "Abstract architectural parti diagrams with bars, voids, and axis lines.",
      palette: "#e2d8c7",
      mode: "minimal_parti",
      seed: "minimal-parti-001",
      controls: [["mass count", 2, 30, 1, 11], ["void ratio", 0, 100, 1, 46], ["axis bias", 0, 100, 1, 58], ["line weight", 1, 9, 1, 3], ["negative space", 5, 90, 1, 54], ["bump", 0, 100, 1, 28], ["displace", 0, 100, 1, 16], ["speed", 0, 100, 1, 24]]
    },
    quiet_grid: {
      title: "noixzy quiet grid",
      concept: "Sparse orthogonal grid with deletions, offsets, and restrained asymmetry.",
      palette: "#c7d8d1",
      mode: "quiet_grid",
      seed: "quiet-grid-001",
      controls: [["grid cells", 6, 60, 1, 22], ["deletion", 0, 100, 1, 48], ["offset", 0, 100, 1, 22], ["line hierarchy", 0, 100, 1, 62], ["asymmetry", 0, 100, 1, 44], ["subdivision", 1, 8, 1, 3], ["bump", 0, 100, 1, 20], ["speed", 0, 100, 1, 14]]
    },
    white_space_field: {
      title: "noixzy white space field",
      concept: "Few architectural masses suspended in a large, controlled negative field.",
      palette: "#d6cab5",
      mode: "white_space_field",
      seed: "white-space-001",
      controls: [["mass count", 1, 24, 1, 7], ["margin", 0, 100, 1, 72], ["alignment", 0, 100, 1, 66], ["tension", 0, 100, 1, 52], ["extrude", 0, 100, 1, 34], ["bump", 0, 100, 1, 24], ["displace", 0, 100, 1, 18], ["palette", 0, 6, 1, 2]]
    },
    modulor_field: {
      title: "noixzy modulor field",
      concept: "Proportion-band generator using modern ratio systems and modular intervals.",
      palette: "#f0c98e",
      mode: "modulor_field",
      seed: "modulor-001",
      controls: [["band count", 2, 40, 1, 14], ["ratio system", 0, 3, 1, 1], ["subdivision", 1, 9, 1, 4], ["accent", 0, 100, 1, 34], ["line weight", 1, 8, 1, 2], ["bump", 0, 100, 1, 18], ["displace", 0, 100, 1, 12], ["speed", 0, 100, 1, 20]]
    },
    brise_soleil: {
      title: "noixzy brise soleil",
      concept: "Kinetic façade fins responding to sun-angle-like phase and rhythm fields.",
      palette: "#bcd7e9",
      mode: "brise_soleil",
      seed: "brise-soleil-001",
      controls: [["fin count", 6, 120, 1, 38], ["tilt", -80, 80, 1, 16], ["sun angle", -90, 90, 1, 20], ["depth", 0, 100, 1, 46], ["line density", 8, 140, 1, 44], ["bump", 0, 100, 1, 22], ["displace", 0, 100, 1, 22], ["speed", 0, 100, 1, 34]]
    },
    aperture_field: {
      title: "noixzy aperture field",
      concept: "Wall apertures generated by view, privacy, and rhythm bias in one field.",
      palette: "#d3c2a7",
      mode: "aperture_field",
      seed: "aperture-001",
      controls: [["aperture count", 4, 140, 1, 34], ["view bias", 0, 100, 1, 58], ["privacy", 0, 100, 1, 36], ["wall depth", 0, 100, 1, 44], ["extrude", 0, 100, 1, 32], ["bump", 0, 100, 1, 16], ["displace", 0, 100, 1, 14], ["seed drift", 0, 100, 1, 22]]
    },
    section_cut: {
      title: "noixzy section cut",
      concept: "Sectional mass slices with floor plates, shafts, and atmospheric depth.",
      palette: "#cdd6dd",
      mode: "section_cut",
      seed: "section-cut-001",
      controls: [["floor count", 2, 40, 1, 11], ["cut depth", 0, 100, 1, 58], ["shaft count", 0, 16, 1, 4], ["poche", 0, 100, 1, 46], ["line weight", 1, 8, 1, 3], ["subdivision", 1, 6, 1, 2], ["bump", 0, 100, 1, 20], ["displace", 0, 100, 1, 18]]
    },
    load_path: {
      title: "noixzy load path",
      concept: "Structural force traces linking supports, beams, and compressed spans.",
      palette: "#d8b6b0",
      mode: "load_path",
      seed: "load-path-001",
      controls: [["node count", 8, 140, 1, 42], ["gravity", 0, 100, 1, 52], ["support spacing", 0, 100, 1, 54], ["tension", 0, 100, 1, 64], ["stiffness", 0, 100, 1, 56], ["line weight", 1, 8, 1, 2], ["bump", 0, 100, 1, 18], ["speed", 0, 100, 1, 26]]
    },
    shadow_louver: {
      title: "noixzy shadow louver",
      concept: "Louver field casting moving shadow bands and phase-interference occlusion.",
      palette: "#bbc7b1",
      mode: "shadow_louver",
      seed: "shadow-louver-001",
      controls: [["louver count", 6, 120, 1, 32], ["pitch", 0, 100, 1, 44], ["rotation", -75, 75, 1, 12], ["shadow softness", 0, 100, 1, 42], ["line density", 8, 160, 1, 54], ["bump", 0, 100, 1, 20], ["displace", 0, 100, 1, 16], ["speed", 0, 100, 1, 28]]
    },
    service_core: {
      title: "noixzy service core",
      concept: "Core-and-plate architecture diagram with shafts, offsets, and served/servant contrast.",
      palette: "#c6c2d8",
      mode: "service_core",
      seed: "service-core-001",
      controls: [["core count", 1, 12, 1, 3], ["plate offset", 0, 100, 1, 38], ["shaft depth", 0, 100, 1, 52], ["served ratio", 0, 100, 1, 62], ["extrude", 0, 100, 1, 30], ["subdivision", 1, 8, 1, 3], ["bump", 0, 100, 1, 18], ["seed drift", 0, 100, 1, 18]]
    }
  };

  function hash(text) { let h = 2166136261; for (let i = 0; i < text.length; i++) { h ^= text.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }
  function random(seed) { let t = hash(seed) || 1; return () => { t += 0x6D2B79F5; let r = Math.imul(t ^ (t >>> 15), 1 | t); r ^= r + Math.imul(r ^ (r >>> 7), 61 | r); return ((r ^ (r >>> 14)) >>> 0) / 4294967296; }; }
  function hsl(h, s, l, a) { return `hsla(${h}, ${s}%, ${l}%, ${a})`; }
  function clampVal(v, min, max) { return Math.max(min, Math.min(max, v)); }

  window.initNoixzyBatch12 = function initNoixzyBatch12(id) {
    const mod = MODULES[id];
    if (!mod) throw new Error("unknown batch 12 module: " + id);
    document.title = mod.title;
    const style = document.createElement("style");
    style.textContent = `:root{color-scheme:dark;--a:${mod.palette};--t:#e8e1d4;--m:#8c877d}*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:#050505;color:var(--t);font-family:ui-monospace,SFMono-Regular,Menlo,monospace}body{display:grid;grid-template-columns:minmax(0,1fr) 292px}main{min-width:0;min-height:0;background:radial-gradient(circle at 50% 25%,rgba(255,255,255,.07),transparent 36%),linear-gradient(#101010,#020202)}canvas{display:block;width:100%;height:100%}aside{border-left:1px solid #2b2b2b;background:#101010;padding:14px;overflow:auto}h1{margin:0 0 5px;font-size:15px;text-transform:lowercase}.sub,.note{color:var(--m);font-size:11px;line-height:1.45}.buttons{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}button{height:34px;border:1px solid #373737;background:#171717;color:var(--t);font:inherit;font-size:11px;cursor:pointer}.row{display:grid;grid-template-columns:44px 1fr;gap:8px;align-items:center;margin-bottom:12px}.row span{font-size:11px;color:var(--m)}input[type=text]{width:100%;background:#080808;border:1px solid #343434;color:var(--t);padding:8px;font:inherit;font-size:11px}.control{border-top:1px solid #222;padding:9px 0}.head{display:flex;justify-content:space-between;font-size:11px;margin-bottom:6px;color:var(--m)}.head b{font-weight:400;color:var(--a)}input[type=range]{width:100%;accent-color:var(--a)}.physics-toggle{display:flex;align-items:center;gap:8px;margin:10px 0 12px;padding:9px 0;border-top:1px solid #222;border-bottom:1px solid #222;color:var(--m);font-size:11px;text-transform:lowercase}.physics-toggle input{accent-color:var(--a)}@media(max-width:760px){body{grid-template-columns:1fr;grid-template-rows:minmax(0,1fr) 315px}aside{border-left:0;border-top:1px solid #2b2b2b}}`;
    document.head.appendChild(style);
    document.body.innerHTML = `<main><canvas id="view"></canvas></main><aside><h1>${mod.title}</h1><p class="sub">${mod.concept}</p><div class="buttons"><button id="play">pause</button><button id="randomize">randomize</button><button id="reset">reset</button><button id="export">export png</button></div><div class="row"><span>seed</span><input id="seed" value="${mod.seed}" spellcheck="false"></div><div id="controls"></div><label class="physics-toggle"><input id="experimental-physics" type="checkbox"> experimental physics</label><p class="note">batch 12: architectural algorithmic expansion for escrow modules.</p></aside>`;

    const canvas = document.getElementById("view");
    const ctx = canvas.getContext("2d");
    const seedEl = document.getElementById("seed");
    const controls = document.getElementById("controls");
    const controlMeta = Object.fromEntries(mod.controls.map(([key, min, max]) => [key, { min, max }]));
    const state = Object.fromEntries(mod.controls.map(c => [c[0], c[4]]));
    let stageBaseState = { ...state };
    let w = 1, h = 1, dpr = 1, frame = 0, running = true;
    let experimentalPhysics = false;
    function snapToStep(value, min, max, step) {
      const safeStep = Number(step) || 1;
      const snapped = Math.round(value / safeStep) * safeStep;
      const clamped = Math.max(Number(min), Math.min(Number(max), snapped));
      return Number.isInteger(safeStep) ? Math.round(clamped) : Number(clamped.toFixed(3));
    }
    function randomBiasFor(key) {
      const k = String(key).toLowerCase();
      if (/palette|material|color|hue/.test(k)) return Math.random();
      if (/density|count|steps|grid|cells|points|nodes|modules|copies|ribbons|rings|lots|pins|markers|bays|divisions|segments|particles|agents|threads|strands|colonies|cracks|repeats/.test(k)) return 0.38 + Math.random() * 0.62;
      if (/extrude|depth|height|stack|layer|relief|bump|displace|amplitude|thickness|width|size|scale|span|vault|socket|scaffold|subdivision|recursion|order|branch|iteration|deflation/.test(k)) return 0.28 + Math.random() * 0.72;
      if (/offset|jitter|noise|field|force|curl|twist|warp|phase|bias|tilt|rotation|entropy|diffusion|oscillation|turbulence|morph|strictness|void|mortar/.test(k)) return 0.12 + Math.random() * 0.76;
      if (/line|stroke|trace|arc/.test(k)) return 0.18 + Math.random() * 0.62;
      return 0.15 + Math.random() * 0.7;
    }
    function randomizeModuleControls() {
      controls.querySelectorAll(".control").forEach(wrap => {
        const input = wrap.querySelector('input[type="range"]');
        if (!input) return;
        const labelNode = wrap.querySelector(".head span, .control-head label");
        const valueNode = wrap.querySelector(".head b, .value");
        const key = labelNode ? labelNode.textContent.trim() : input.id;
        const min = Number(input.min), max = Number(input.max), step = Number(input.step) || 1;
        const value = snapToStep(min + (max - min) * randomBiasFor(key), min, max, step);
        input.value = value;
        input.dispatchEvent(new Event("input", { bubbles: true }));
        if (valueNode) valueNode.textContent = value;
      });
      experimentalPhysics = Math.random() > 0.55;
      const physics = document.getElementById("experimental-physics");
      if (physics) physics.checked = experimentalPhysics;
      applyExperimentalPhysics();
    }
    function applyExperimentalPhysics() {
      const dx = experimentalPhysics ? Math.sin(frame * 0.017) * 4.5 : 0;
      const dy = experimentalPhysics ? Math.cos(frame * 0.013) * 3.5 : 0;
      const breathe = experimentalPhysics ? 1 + Math.sin(frame * 0.011) * 0.004 : 1;
      canvas.style.transformOrigin = "50% 50%";
      canvas.style.transform = experimentalPhysics ? `translate3d(${dx}px, ${dy}px, 0) scale(${breathe})` : "";
      canvas.style.filter = experimentalPhysics ? "contrast(1.06) saturate(1.08)" : "";
    }


    mod.controls.forEach(([key, min, max, step]) => {
      const div = document.createElement("div");
      div.className = "control";
      div.innerHTML = `<div class="head"><span>${key}</span><b>${state[key]}</b></div><input type="range" min="${min}" max="${max}" step="${step}" value="${state[key]}">`;
      controls.appendChild(div);
      div.querySelector("input").oninput = e => {
        state[key] = Number(e.target.value);
        stageBaseState[key] = state[key];
        div.querySelector("b").textContent = state[key];
        draw(true);
      };
    });

    function applyStateToUi() {
      controls.querySelectorAll(".control").forEach(div => {
        const key = div.querySelector(".head span").textContent;
        const input = div.querySelector("input");
        const value = div.querySelector(".head b");
        if (Object.prototype.hasOwnProperty.call(state, key)) {
          input.value = state[key];
          value.textContent = state[key];
        }
      });
    }

    function drive(keys, blend) {
      keys.forEach(key => {
        if (!Object.prototype.hasOwnProperty.call(state, key)) return;
        const meta = controlMeta[key];
        if (!meta) return;
        const span = meta.max - meta.min;
        state[key] = clampVal(stageBaseState[key] + span * blend, meta.min, meta.max);
      });
    }

    function applyStageParams(stage) {
      if (!stage || typeof stage !== "object") return;
      const geom = clampVal((Math.abs(stage.depth) / 260 + Math.abs(stage.rotateX) / 55 + Math.abs(stage.rotateY) / 55) / 3, 0, 1);
      const arrayEnergy = clampVal(((stage.arrayCount - 1) / 8) * 0.7 + (stage.arraySpread / 180) * 0.3, 0, 1);
      const kitbashEnergy = stage.kitbash === "none" ? 0 : clampVal((stage.kitbashDensity / 14) * 0.55 + (stage.kitbashScale / 140) * 0.45, 0, 1);
      const materialEnergy = clampVal((stage.material + 80) / 160, 0, 1);
      const tempo = clampVal((stage.zoom - 55) / 90, 0, 1);
      Object.assign(state, stageBaseState);
      drive(["mass count", "grid cells", "band count", "fin count", "aperture count", "floor count", "node count", "louver count", "core count"], (arrayEnergy + kitbashEnergy) * 0.22);
      drive(["speed", "seed drift"], tempo * 0.24 + arrayEnergy * 0.06);
      drive(["line weight", "line density", "line hierarchy"], (kitbashEnergy + materialEnergy) * 0.2 - 0.08);
      drive(["extrude", "cut depth", "depth", "shaft depth", "wall depth"], (geom + arrayEnergy) * 0.3 - 0.08);
      drive(["bump"], (materialEnergy + kitbashEnergy) * 0.32 - 0.1);
      drive(["displace", "offset", "plate offset", "tilt", "rotation", "sun angle"], (geom + arrayEnergy) * 0.2 + ((stage.rotateY || 0) / 55) * 0.12);
      drive(["subdivision"], (geom + kitbashEnergy) * 0.16);
      drive(["palette"], (materialEnergy - 0.5) * 0.9);
      applyStateToUi();
      draw(true);
    }


    const physicsToggle = document.getElementById("experimental-physics");
    if (physicsToggle) physicsToggle.onchange = () => { experimentalPhysics = physicsToggle.checked; applyExperimentalPhysics(); draw(true); };

    function resize() {
      dpr = Math.max(1, Math.min(2, devicePixelRatio || 1));
      const r = canvas.getBoundingClientRect();
      w = Math.max(320, r.width);
      h = Math.max(260, r.height);
      canvas.width = w * dpr;
      canvas.height = h * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      draw(true);
    }

    function rect3(x, y, ww, hh, dep, fill) {
      ctx.fillStyle = fill;
      ctx.fillRect(x, y, ww, hh);
      ctx.fillStyle = "rgba(255,255,255,.1)";
      ctx.beginPath();
      ctx.moveTo(x, y);
      ctx.lineTo(x + dep, y - dep * 0.45);
      ctx.lineTo(x + ww + dep, y - dep * 0.45);
      ctx.lineTo(x + ww, y);
      ctx.closePath();
      ctx.fill();
      ctx.fillStyle = "rgba(0,0,0,.32)";
      ctx.beginPath();
      ctx.moveTo(x + ww, y);
      ctx.lineTo(x + ww + dep, y - dep * 0.45);
      ctx.lineTo(x + ww + dep, y + hh - dep * 0.45);
      ctx.lineTo(x + ww, y + hh);
      ctx.closePath();
      ctx.fill();
    }

    function draw(full) {
      const R = random(seedEl.value + mod.mode);
      const speedFactor = (state.speed || 25) / 30;
      const t = frame * 0.01 * speedFactor;
      const cx = w * 0.5;
      const cy = h * 0.5;
      ctx.clearRect(0, 0, w, h);
      ctx.fillStyle = full ? "#070707" : "rgba(7,7,7,.93)";
      ctx.fillRect(0, 0, w, h);
      ctx.strokeStyle = mod.palette;
      ctx.fillStyle = mod.palette;
      ctx.lineJoin = "round";
      ctx.lineCap = "round";

      if (mod.mode === "minimal_parti" || mod.mode === "white_space_field") {
        const count = state["mass count"];
        const margin = (state.margin || state["negative space"] || 40) / 100;
        const box = Math.min(w, h) * (1 - margin * 0.65);
        for (let i = 0; i < count; i++) {
          if (R() * 100 < (state["void ratio"] || 20)) continue;
          const ww = box * (0.08 + R() * 0.24);
          const hh = box * (0.06 + R() * 0.2);
          const x = cx - box * 0.5 + R() * (box - ww) + Math.sin(i + t) * (state.displace || 0) * 0.15;
          const y = cy - box * 0.5 + R() * (box - hh);
          rect3(x, y, ww, hh, (state.extrude || 0) * 0.2 + (state.bump || 0) * 0.06, hsl(32 + i * 7, 18, 14 + (i % 4) * 5, 0.88));
          ctx.strokeStyle = hsl(42, 35, 70, 0.34 + (state["line weight"] || 2) * 0.04);
          ctx.lineWidth = Math.max(1, state["line weight"] || 2);
          ctx.strokeRect(x, y, ww, hh);
        }
        ctx.globalAlpha = 0.34;
        for (let i = 0; i < 4; i++) {
          const y = cy - box * 0.5 + i * box * 0.33 + (state["axis bias"] || state.alignment || 50) * 0.05;
          ctx.beginPath(); ctx.moveTo(cx - box * 0.56, y); ctx.lineTo(cx + box * 0.56, y); ctx.stroke();
        }
        ctx.globalAlpha = 1;
      } else if (mod.mode === "quiet_grid" || mod.mode === "modulor_field") {
        const cells = state["grid cells"] || state["band count"];
        const pad = 28;
        const cw = (w - pad * 2) / cells;
        const ch = (h - pad * 2) / cells;
        for (let y = 0; y < cells; y++) for (let x = 0; x < cells; x++) {
          if (R() * 100 < (state.deletion || 0)) continue;
          const px = pad + x * cw + Math.sin((x + y) * .5 + t) * (state.offset || state.displace || 0) * 0.04;
          const py = pad + y * ch;
          const tone = 10 + ((x + y) % 5) * 4 + (state.accent || 0) * 0.04;
          ctx.fillStyle = hsl(38 + (state["ratio system"] || 0) * 22 + (state.palette || 0) * 16, 18, tone, 0.82);
          ctx.fillRect(px, py, cw * 0.88, ch * 0.88);
          ctx.strokeStyle = hsl(38, 28, 70, 0.2 + (state["line hierarchy"] || state["line weight"] || 20) * 0.004);
          ctx.lineWidth = Math.max(1, (state["line weight"] || 2) * 0.8);
          ctx.strokeRect(px, py, cw * 0.88, ch * 0.88);
        }
      } else if (mod.mode === "brise_soleil" || mod.mode === "shadow_louver") {
        const n = state["fin count"] || state["louver count"];
        const step = (w - 80) / Math.max(1, n);
        const baseY = h * 0.15;
        for (let i = 0; i < n; i++) {
          const x = 40 + i * step;
          const wave = Math.sin(i * 0.33 + t + (state["sun angle"] || 0) * 0.03);
          const rot = (state.tilt || state.rotation || 0) * 0.03 + wave;
          const depth = (state.depth || 40) * 0.35;
          const hh = h * (0.64 + (state.displace || 0) * 0.0015);
          ctx.save();
          ctx.translate(x, baseY + hh * 0.5);
          ctx.rotate(rot * 0.18);
          rect3(-step * 0.2, -hh * 0.5, step * 0.4, hh, depth, hsl(196 + i * 0.6, 20, 16 + (i % 3) * 4, 0.86));
          ctx.restore();
          ctx.fillStyle = `rgba(0,0,0,${0.08 + (state["shadow softness"] || 30) * 0.004})`;
          ctx.fillRect(x + depth * 0.4, baseY, step * 0.33, hh);
        }
      } else if (mod.mode === "aperture_field" || mod.mode === "service_core") {
        const count = state["aperture count"] || state["core count"] * 8;
        const wall = { x: w * 0.12, y: h * 0.14, ww: w * 0.76, hh: h * 0.72 };
        rect3(wall.x, wall.y, wall.ww, wall.hh, (state["wall depth"] || state["shaft depth"] || 40) * 0.3, "#1a1815");
        for (let i = 0; i < count; i++) {
          const ww = 12 + R() * 52 * (0.5 + (state["view bias"] || state["served ratio"] || 50) * 0.01);
          const hh = 10 + R() * 46 * (0.5 + (100 - (state.privacy || 40)) * 0.01);
          const x = wall.x + 8 + R() * (wall.ww - ww - 16);
          const y = wall.y + 8 + R() * (wall.hh - hh - 16);
          ctx.fillStyle = "rgba(0,0,0,.78)";
          ctx.fillRect(x, y, ww, hh);
          ctx.strokeStyle = hsl(39 + (state.palette || 0) * 17, 26, 66, 0.3 + (state.bump || 0) * 0.003);
          ctx.lineWidth = Math.max(1, (state.extrude || 20) * 0.03);
          ctx.strokeRect(x, y, ww, hh);
        }
      } else if (mod.mode === "section_cut") {
        const floors = state["floor count"];
        const floorH = (h * 0.72) / floors;
        const x0 = w * 0.15;
        for (let i = 0; i < floors; i++) {
          const y = h * 0.14 + i * floorH;
          const ww = w * (0.66 + Math.sin(i * 0.9 + t) * (state.displace || 0) * 0.0012);
          rect3(x0, y, ww, floorH * 0.82, (state["cut depth"] || 40) * 0.2, hsl(205, 12, 12 + (i % 4) * 5 + (state.poche || 0) * 0.02, 0.9));
          ctx.strokeStyle = hsl(38, 18, 72, 0.2 + (state["line weight"] || 2) * 0.06);
          ctx.lineWidth = Math.max(1, state["line weight"] || 2);
          ctx.beginPath(); ctx.moveTo(x0 - 20, y + floorH * 0.82); ctx.lineTo(x0 + ww + 20, y + floorH * 0.82); ctx.stroke();
        }
        for (let i = 0; i < state["shaft count"]; i++) {
          const sx = x0 + 40 + i * ((w * 0.56) / Math.max(1, state["shaft count"]));
          ctx.fillStyle = "rgba(0,0,0,.68)";
          ctx.fillRect(sx, h * 0.14, 14 + (state.subdivision || 1) * 2, h * 0.72);
        }
      } else if (mod.mode === "load_path") {
        const n = state["node count"];
        const pts = [];
        for (let i = 0; i < n; i++) {
          const x = 40 + (i / Math.max(1, n - 1)) * (w - 80);
          const y = h * (0.28 + Math.sin(i * 0.31 + t) * 0.18 + (state.gravity - 50) * 0.002);
          pts.push([x, y]);
        }
        ctx.strokeStyle = hsl(12, 46, 62, 0.58);
        ctx.lineWidth = Math.max(1, state["line weight"] || 2);
        for (let i = 0; i < n - 1; i++) {
          const p = pts[i], q = pts[i + 1];
          ctx.beginPath();
          ctx.moveTo(p[0], p[1]);
          ctx.quadraticCurveTo((p[0] + q[0]) * 0.5, h * (0.52 + (state.tension - state.stiffness) * 0.003), q[0], q[1]);
          ctx.stroke();
        }
        ctx.fillStyle = hsl(32, 26, 72, 0.86);
        pts.forEach(p => { ctx.beginPath(); ctx.arc(p[0], p[1], 1.5 + (state.bump || 0) * 0.025, 0, Math.PI * 2); ctx.fill(); });
      }

      ctx.fillStyle = "rgba(232,225,212,.68)";
      ctx.font = "11px ui-monospace,monospace";
      ctx.fillText(seedEl.value, 16, h - 18);
    }

    function tick() { if (running) { frame++; applyExperimentalPhysics(); draw(false); } requestAnimationFrame(tick); }
    document.getElementById("play").onclick = () => { running = !running; document.getElementById("play").textContent = running ? "pause" : "play"; draw(true); };
    document.getElementById("randomize").onclick = () => { seedEl.value = mod.mode + "-" + Math.floor(Math.random() * 999999).toString(36); randomizeModuleControls(); stageBaseState = { ...state }; draw(true); };
    document.getElementById("reset").onclick = () => location.reload();
    document.getElementById("export").onclick = () => { draw(true); const a = document.createElement("a"); a.download = id + ".png"; a.href = canvas.toDataURL("image/png"); a.click(); };
    seedEl.oninput = () => draw(true);
    window.addEventListener("message", event => {
      if (!event.data || event.data.type !== "noixzy:stage-params") return;
      applyStageParams(event.data.stage);
    });
    window.addEventListener("resize", resize);
    resize();
    applyExperimentalPhysics();
    tick();
  };
})();
