(function(){
  "use strict";
  const MODULES = {
    peano:{title:"noixzy peano curve archipelago",concept:"Peano space-filling coastlines, island blocks, and recursive urban water gaps.",accent:"#9fc9b8",seed:"peano-archipelago-001",controls:[["order",1,5,1,4],["cell scale",4,22,1,10],["coast warp",0,100,1,42],["island fill",0,100,1,54],["stack depth",0,100,1,38],["line weight",1,7,1,2],["nano docks",0,100,1,34],["palette",0,5,1,1]]},
    gaussian:{title:"noixzy gaussian integer orbits",concept:"Complex integer lattices with modular orbit shells, residue glow, and polar scaffolds.",accent:"#b5c7e8",seed:"gaussian-orbits-001",controls:[["grid radius",5,30,1,16],["modulus",2,19,1,7],["orbit steps",20,260,1,120],["shell count",1,10,1,5],["field strength",0,100,1,46],["dot size",1,7,1,2],["line weight",1,6,1,1],["palette",0,5,1,2]]},
    dragon:{title:"noixzy dragon curve scaffold",concept:"Heighway dragon folds converted into architectural ribs and nested brace systems.",accent:"#d7b285",seed:"dragon-scaffold-001",controls:[["iterations",5,15,1,11],["segment",2,14,1,6],["fold bias",-80,80,1,12],["brace density",0,100,1,48],["extrude",0,100,1,42],["jitter",0,100,1,16],["line weight",1,7,1,2],["palette",0,5,1,4]]},
    menger:{title:"noixzy menger void array",concept:"Recursive cube-void logic flattened into stacked portals, frames, and nano apertures.",accent:"#cfc2a3",seed:"menger-void-001",controls:[["recursion",1,5,1,3],["block scale",20,140,1,76],["void bias",0,100,1,62],["array copies",1,9,1,4],["extrude",0,100,1,58],["bump",0,100,1,35],["line weight",1,8,1,2],["palette",0,5,1,0]]},
    julia:{title:"noixzy julia contour relic",concept:"Complex Julia escape contours as etched relic plates with raised threshold bands.",accent:"#c7b3e6",seed:"julia-relic-001",controls:[["iterations",20,160,1,72],["cx",-100,100,1,-62],["cy",-100,100,1,38],["zoom",30,180,1,90],["threshold",0,100,1,52],["contour bands",2,18,1,9],["bump",0,100,1,42],["palette",0,5,1,5]]},
    turing:{title:"noixzy turing morphogenesis field",concept:"Reaction-inhibition style spots, stripes, cells, and biological mask geometry.",accent:"#a6d0a2",seed:"turing-field-001",controls:[["cell size",3,14,1,7],["activator",0,100,1,55],["inhibitor",0,100,1,44],["stripe bias",0,100,1,38],["threshold",0,100,1,54],["relief depth",0,100,1,45],["noise",0,100,1,24],["palette",0,5,1,1]]},
    eden:{title:"noixzy eden percolation sprawl",concept:"Stochastic colony growth and percolation corridors forming lichen-like city tissue.",accent:"#c9d19a",seed:"eden-sprawl-001",controls:[["growth steps",60,1200,1,520],["seed count",1,28,1,9],["anisotropy",-100,100,1,22],["cell size",3,18,1,8],["corridor bias",0,100,1,48],["extrude",0,100,1,32],["edge roughness",0,100,1,54],["palette",0,5,1,3]]},
    triangulated:{title:"noixzy triangulated signal mesh",concept:"Delaunay-like signal facets, jittered point clouds, and tensioned mesh relief.",accent:"#a4c7d4",seed:"triangulated-signal-001",controls:[["point count",20,220,1,96],["connection radius",20,180,1,84],["jitter",0,100,1,42],["signal warp",0,100,1,55],["facet fill",0,100,1,36],["line weight",1,6,1,1],["bump",0,100,1,28],["palette",0,5,1,2]]},
    miura:{title:"noixzy origami miura fold",concept:"Miura-ori fold tessellations with alternating mountain/valley depth and plate shimmer.",accent:"#d6c897",seed:"miura-fold-001",controls:[["columns",4,32,1,16],["rows",3,24,1,11],["fold angle",0,100,1,62],["depth",0,100,1,50],["skew",-80,80,1,18],["crease weight",1,8,1,2],["shimmer",0,100,1,36],["palette",0,5,1,4]]},
    grayscott:{title:"noixzy grayscott preset bank",concept:"Curated Gray-Scott-inspired preset families: mitosis, coral, worms, holes, and soliton bands.",accent:"#d99aa4",seed:"grayscott-bank-001",controls:[["preset",0,6,1,2],["cell size",3,16,1,7],["feed",0,100,1,42],["kill",0,100,1,58],["diffusion",0,100,1,50],["iterations",1,24,1,10],["bump",0,100,1,40],["palette",0,5,1,3]]}
  };
  const PALETTES=[["#070707","#d8c9aa","#8fc8c2"],["#050706","#a8d0ad","#e4d8b6"],["#05080b","#9dc7ff","#e8c779"],["#090805","#d4bd84","#9bb7d2"],["#090606","#d2a487","#d8c9aa"],["#08070a","#c7b2df","#80d6d0"]];
  const TAU=Math.PI*2;
  function hash(t){let h=2166136261; for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619);} return h>>>0;}
  function rng(seed){let t=hash(seed)||1; return()=>{t+=0x6D2B79F5; let r=Math.imul(t^(t>>>15),1|t); r^=r+Math.imul(r^(r>>>7),61|r); return ((r^(r>>>14))>>>0)/4294967296;};}
  function hsl(h,s,l,a){return 'hsla('+h+', '+s+'%, '+l+'%, '+a+')';}
  function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
  function rect3(ctx,x,y,w,h,d,fill){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);ctx.fillStyle="rgba(255,255,255,.10)";ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+d,y-d*.45);ctx.lineTo(x+w+d,y-d*.45);ctx.lineTo(x+w,y);ctx.closePath();ctx.fill();ctx.fillStyle="rgba(0,0,0,.34)";ctx.beginPath();ctx.moveTo(x+w,y);ctx.lineTo(x+w+d,y-d*.45);ctx.lineTo(x+w+d,y+h-d*.45);ctx.lineTo(x+w,y+h);ctx.closePath();ctx.fill();}
  window.initNoixzyBatch15=function(id){
    const mod=MODULES[id]; if(!mod) throw new Error('unknown batch 15 module: '+id); document.title=mod.title;
    const style=document.createElement('style'); style.textContent=':root{color-scheme:dark;--a:'+mod.accent+';--t:#e8e1d4;--m:#8c877d}*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:#050505;color:var(--t);font-family:ui-monospace,SFMono-Regular,Menlo,monospace}body{display:grid;grid-template-columns:minmax(0,1fr) 292px}main{min-width:0;min-height:0;background:radial-gradient(circle at 50% 24%,rgba(255,255,255,.07),transparent 36%),linear-gradient(#101010,#020202)}canvas{display:block;width:100%;height:100%}aside{border-left:1px solid #2b2b2b;background:#101010;padding:14px;overflow:auto}h1{margin:0 0 5px;font-size:15px;text-transform:lowercase}.sub,.note{color:var(--m);font-size:11px;line-height:1.45}.buttons{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}button{height:34px;border:1px solid #373737;background:#171717;color:var(--t);font:inherit;font-size:11px;cursor:pointer}.row{display:grid;grid-template-columns:44px 1fr;gap:8px;align-items:center;margin-bottom:12px}.row span{font-size:11px;color:var(--m)}input[type=text]{width:100%;background:#080808;border:1px solid #343434;color:var(--t);padding:8px;font:inherit;font-size:11px}.control{border-top:1px solid #222;padding:9px 0}.head{display:flex;justify-content:space-between;font-size:11px;margin-bottom:6px;color:var(--m)}.head b{font-weight:400;color:var(--a)}input[type=range]{width:100%;accent-color:var(--a)}.physics-toggle{display:flex;align-items:center;gap:8px;margin:10px 0 12px;padding:9px 0;border-top:1px solid #222;border-bottom:1px solid #222;color:var(--m);font-size:11px;text-transform:lowercase}.physics-toggle input{accent-color:var(--a)}@media(max-width:760px){body{grid-template-columns:1fr;grid-template-rows:minmax(0,1fr) 315px}aside{border-left:0;border-top:1px solid #2b2b2b}}'; document.head.appendChild(style);
    document.body.innerHTML='<main><canvas id="view"></canvas></main><aside><h1>'+mod.title+'</h1><p class="sub">'+mod.concept+'</p><div class="buttons"><button id="play">pause</button><button id="randomize">randomize</button><button id="reset">reset</button><button id="export">export png</button></div><div class="row"><span>seed</span><input id="seed" value="'+mod.seed+'" spellcheck="false"></div><div id="controls"></div><label class="physics-toggle"><input id="experimental-physics" type="checkbox"> experimental physics</label><p class="note">batch 15: generated from workspace algorithmic-art notes; module-level recursion, fields, thresholds, folds, and nano geometry.</p></aside>';
    const canvas=document.getElementById('view'),ctx=canvas.getContext('2d'),controls=document.getElementById('controls'),seedEl=document.getElementById('seed');
    const state=Object.fromEntries(mod.controls.map(c=>[c[0],c[4]])); let w=1,h=1,dpr=1,frame=0,running=true,physics=false;
    mod.controls.forEach(([key,min,max,step])=>{const div=document.createElement('div');div.className='control';div.innerHTML='<div class="head"><span>'+key+'</span><b>'+state[key]+'</b></div><input type="range" min="'+min+'" max="'+max+'" step="'+step+'" value="'+state[key]+'">';controls.appendChild(div);div.querySelector('input').oninput=e=>{state[key]=Number(e.target.value);div.querySelector('b').textContent=state[key];draw(true);};});
    function pal(){return PALETTES[Math.abs(Math.floor(state.palette||0))%PALETTES.length];}
    function snap(v,min,max,step){return clamp(Math.round(v/step)*step,min,max);}
    function bias(k){k=String(k).toLowerCase(); if(/palette|preset/.test(k))return Math.random(); if(/count|grid|rows|columns|steps|iterations|order|recursion|points|copies|bands|shell/.test(k))return .38+Math.random()*.62; if(/extrude|depth|bump|relief|scale|size|weight|radius|segment/.test(k))return .25+Math.random()*.75; return .12+Math.random()*.76;}
    function randomize(){seedEl.value=id+'-'+Math.floor(Math.random()*999999).toString(36);controls.querySelectorAll('.control').forEach(div=>{const input=div.querySelector('input'), key=div.querySelector('.head span').textContent, min=+input.min,max=+input.max,step=+input.step||1;const v=snap(min+(max-min)*bias(key),min,max,step);input.value=v;state[key]=v;div.querySelector('b').textContent=v;});physics=Math.random()>.55;document.getElementById('experimental-physics').checked=physics;applyPhysics();draw(true);}
    function applyPhysics(){canvas.style.transformOrigin='50% 50%';canvas.style.transform=physics?'translate3d('+Math.sin(frame*.017)*4+'px,'+Math.cos(frame*.013)*3+'px,0) scale('+(1+Math.sin(frame*.011)*.004)+')':'';canvas.style.filter=physics?'contrast(1.06) saturate(1.08)':'';}
    function resize(){dpr=Math.max(1,Math.min(2,devicePixelRatio||1));const r=canvas.getBoundingClientRect();w=Math.max(320,r.width);h=Math.max(260,r.height);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw(true);}
    function clear(){const p=pal();ctx.fillStyle=p[0];ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.05)';}
    function draw(){clear(); const p=pal(),R=rng(seedEl.value+id),cx=w/2,cy=h/2,t=frame*.012;ctx.lineCap='round';ctx.lineJoin='round';
      if(id==='peano'){let n=Math.pow(3,state.order),s=Math.min(w,h)*.82/n,ox=(w-s*n)/2,oy=(h-s*n)/2;ctx.strokeStyle=p[1];ctx.lineWidth=state['line weight'];ctx.beginPath();for(let i=0;i<n*n;i++){let x=i%n,y=Math.floor(i/n);if(y%2)x=n-1-x;let px=ox+x*s+Math.sin(i*.7+t)*state['coast warp']*.03,py=oy+y*s+Math.cos(i*.4)*state['coast warp']*.03;i?ctx.lineTo(px,py):ctx.moveTo(px,py);if(R()*100<state['island fill']*.03)rect3(ctx,px,py,s*.8,s*.58,state['stack depth']*.08,p[2]);if(R()*100<state['nano docks']*.02){ctx.fillStyle=p[2];ctx.fillRect(px,py,2,8);}}ctx.stroke();}
      else if(id==='gaussian'){let gr=state['grid radius'],scale=Math.min(w,h)*.42/gr;for(let a=-gr;a<=gr;a++)for(let b=-gr;b<=gr;b++){let m=((a*a+b*b)%state.modulus),x=cx+a*scale+Math.sin((b+m)*.8+t)*state['field strength']*.05,y=cy+b*scale+Math.cos((a-m)*.7)*state['field strength']*.05;if(m<state['shell count']){ctx.fillStyle=hsl(205+m*24+state.palette*18,35,48,.72);ctx.beginPath();ctx.arc(x,y,state['dot size']+m*.12,0,TAU);ctx.fill();if(m%2===0){ctx.strokeStyle=p[2];ctx.lineWidth=state['line weight']*.45;ctx.beginPath();ctx.arc(cx,cy,Math.hypot(a,b)*scale,0,TAU);ctx.stroke();}}}}
      else if(id==='dragon'){let pts=[[cx,cy]],dir=0,seg=state.segment*1.5;for(let i=0;i<state.iterations;i++){let turn=i%2?1:-1;let copy=[];for(let j=pts.length-1;j>=0;j--)copy.push(pts[j]);let last=pts[pts.length-1];copy.forEach((pt,k)=>{dir+=(turn*(k%2?1:-1))*Math.PI/2+state['fold bias']*.0007;last=[last[0]+Math.cos(dir)*seg,last[1]+Math.sin(dir)*seg];pts.push([last[0]+(R()-.5)*state.jitter*.05,last[1]+(R()-.5)*state.jitter*.05]);}); if(pts.length>6000)break;}ctx.strokeStyle=p[1];ctx.lineWidth=state['line weight'];ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]));ctx.stroke();ctx.strokeStyle=p[2];for(let i=0;i<pts.length;i+=Math.max(3,Math.floor(120-state['brace density']))){let q=pts[i],r=pts[(i+13)%pts.length];ctx.beginPath();ctx.moveTo(q[0]+state.extrude*.04,q[1]-state.extrude*.03);ctx.lineTo(r[0],r[1]);ctx.stroke();}}
      else if(id==='menger'){function rec(x,y,s,d){if(d<=0){rect3(ctx,x,y,s,s*.72,state.extrude*.12,p[(Math.floor(x+y))%2?1:2]);return;}let ns=s/3;for(let yy=0;yy<3;yy++)for(let xx=0;xx<3;xx++){let hole=(xx===1&&yy===1)||R()*100<state['void bias']*.08;if(!hole)rec(x+xx*ns,y+yy*ns,ns,d-1);}}for(let c=0;c<state['array copies'];c++){let s=state['block scale']*(1+c*.12),x=cx-s/2+(c-(state['array copies']-1)/2)*s*.72,y=cy-s*.42+c*5;rec(x,y,s,state.recursion);}ctx.lineWidth=state['line weight'];}
      else if(id==='julia'){let cell=5,iter=state.iterations,cxv=state.cx/100,cyv=state.cy/100,zoom=state.zoom/75;for(let y=0;y<h;y+=cell)for(let x=0;x<w;x+=cell){let zx=(x-w/2)/(Math.min(w,h)*.34)*zoom,zy=(y-h/2)/(Math.min(w,h)*.34)*zoom,k=0;for(;k<iter;k++){let nx=zx*zx-zy*zy+cxv,ny=2*zx*zy+cyv;zx=nx;zy=ny;if(zx*zx+zy*zy>4)break;}let band=k%state['contour bands'];if(k>state.threshold*.01*iter){ctx.fillStyle=hsl(260+band*14+state.palette*18,24,16+band*3+state.bump*.08,.76);ctx.fillRect(x,y,cell,cell);}}}
      else if(id==='turing'){let cs=state['cell size'];for(let y=0;y<h;y+=cs)for(let x=0;x<w;x+=cs){let nx=x*.018+state.noise*.002,ny=y*.018;let v=Math.sin(nx*state.activator*.05+Math.cos(ny*2+t))*Math.cos(ny*state.inhibitor*.04)+Math.sin((x+y)*.02+state['stripe bias']*.04);if(v>state.threshold/60-1.2){let fill=hsl(92+v*24+state.palette*20,26,28+state['relief depth']*.12,.82);rect3(ctx,x,y,cs*.9,cs*.9,state['relief depth']*.035,fill);}}}
      else if(id==='eden'){let cs=state['cell size'],cols=Math.floor(w/cs),rows=Math.floor(h/cs),live=new Set(),front=[];for(let i=0;i<state['seed count'];i++){let x=Math.floor(cols*(.2+R()*.6)),y=Math.floor(rows*(.2+R()*.6));live.add(x+','+y);front.push([x,y]);}for(let i=0;i<state['growth steps']&&front.length;i++){let base=front[Math.floor(R()*front.length)],dirs=[[1,0],[-1,0],[0,1],[0,-1]];let d=dirs[Math.floor(R()*4)];if(state.anisotropy>0&&R()<Math.abs(state.anisotropy)/120)d=[1,0];if(state.anisotropy<0&&R()<Math.abs(state.anisotropy)/120)d=[0,1];let x=clamp(base[0]+d[0],1,cols-2),y=clamp(base[1]+d[1],1,rows-2),k=x+','+y;if(!live.has(k)){live.add(k);front.push([x,y]);}}live.forEach(k=>{let [x,y]=k.split(',').map(Number);rect3(ctx,x*cs,y*cs,cs*.86,cs*.86,state.extrude*.04,hsl(68+state.palette*20,25,18+R()*20,.85));});}
      else if(id==='triangulated'){let pts=[];for(let i=0;i<state['point count'];i++)pts.push([w*(.1+R()*.8)+(R()-.5)*state.jitter,h*(.12+R()*.76)+(R()-.5)*state.jitter]);ctx.lineWidth=state['line weight'];for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){let a=pts[i],b=pts[j],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(d<state['connection radius']){ctx.strokeStyle='rgba(164,199,212,'+(.12+(1-d/state['connection radius'])*.35)+')';ctx.beginPath();ctx.moveTo(a[0]+Math.sin(t+i)*state['signal warp']*.05,a[1]);ctx.lineTo(b[0],b[1]+Math.cos(t+j)*state['signal warp']*.05);ctx.stroke();}}pts.forEach(q=>{ctx.fillStyle=p[2];ctx.fillRect(q[0]-state.bump*.015,q[1],2+state.bump*.02,2+state.bump*.02);});}
      else if(id==='miura'){let cols=state.columns,rows=state.rows,cw=w*.82/cols,ch=h*.72/rows,ox=w*.09,oy=h*.14,sk=state.skew*.05;ctx.lineWidth=state['crease weight'];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){let px=ox+x*cw+(y%2?sk:0),py=oy+y*ch,alt=(x+y)%2,dep=(alt?1:-1)*state.depth*.08;ctx.fillStyle=hsl(42+state.palette*20,20,18+alt*8+state.shimmer*.08,.86);ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(px+cw,py+dep);ctx.lineTo(px+cw+sk,py+ch);ctx.lineTo(px+sk,py+ch-dep);ctx.closePath();ctx.fill();ctx.strokeStyle=alt?p[1]:p[2];ctx.stroke();}}
      else if(id==='grayscott'){let preset=state.preset,cs=state['cell size'];for(let y=0;y<h;y+=cs)for(let x=0;x<w;x+=cs){let nx=x*.025,ny=y*.025,v=Math.sin(nx*(1+preset*.22)+t)*Math.cos(ny*(1.2+state.feed*.01))+Math.sin((nx+ny)*state.diffusion*.015+preset);v+=Math.sin(Math.hypot(x-cx,y-cy)*.045-state.kill*.04);let pass=v>state.feed/70-1;if(pass){let fill=hsl(330+preset*22+state.palette*18,28,22+v*12+state.bump*.08,.78);rect3(ctx,x,y,cs*.9,cs*.9,state.bump*.035,fill);}}}
      ctx.globalAlpha=1;ctx.fillStyle='rgba(232,225,212,.68)';ctx.font='11px ui-monospace,monospace';ctx.fillText(seedEl.value,16,h-18);
    }
    function tick(){if(running){frame++;applyPhysics();draw(false);}requestAnimationFrame(tick);} document.getElementById('play').onclick=()=>{running=!running;document.getElementById('play').textContent=running?'pause':'play';draw(true);};document.getElementById('randomize').onclick=randomize;document.getElementById('reset').onclick=()=>location.reload();document.getElementById('export').onclick=()=>{draw(true);const a=document.createElement('a');a.download=id+'.png';a.href=canvas.toDataURL('image/png');a.click();};document.getElementById('experimental-physics').onchange=e=>{physics=e.target.checked;applyPhysics();draw(true);};seedEl.oninput=()=>draw(true);addEventListener('resize',resize);resize();tick();
  };
})();
